spring.application.name=videoLocadora

spring.datasource.url=jdbc:postgresql://localhost:5432/videoLocadora
spring.datasource.username=postgres
# Senha Marco
spring.datasource.password=postgres 
# Senha Ronan
# spring.datasource.password=33218600 

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
